# Generated by Django 5.1.7 on 2025-05-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_categories', '0002_expensecategory_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
