# Generated by Django 5.1.7 on 2025-05-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_categories', '0004_alter_expensecategory_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
