# Generated by Django 5.1.7 on 2025-06-05 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_deleted_at_customuser_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='spending_limit',
        ),
    ]
