# Generated by Django 5.1.7 on 2025-05-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_categories', '0002_alter_incomecategory_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='incomecategory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='incomecategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
