# Generated by Django 5.1.7 on 2025-03-17 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rolepermission',
            table='tbl_role_permissions',
        ),
    ]
