# Generated by Django 5.1.7 on 2025-03-20 18:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0004_permission_created_at_permission_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
