# Generated by Django 5.1.7 on 2025-05-12 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='amount',
            new_name='income_amount',
        ),
    ]
