# Generated by Django 5.1.7 on 2025-03-17 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='role',
            table='tbl_roles',
        ),
    ]
